plot-worlds:
  - plotworld
  - creative
  - redstonerank

# Valid item names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Ensure you use all caps, and properly format the list!
# DIODE_BLOCK_ON/OFF is equal to a REPEATER but for 1.12
prohibit-interact-items:
  - REPEATER
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - COMPARATOR
  - HOPPER
  - STONE_BUTTON
  - IRON_DOOR
  - JUNGLE_DOOR
  - JUNGLE_BUTTON
  - DISPENSER
  - DROPPER

# Valid entity names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# Please only use mobs... Won't break otherwise, but won't make much sense
# Ensure you use all caps, and properly format the list!
prohibit-interact-entities:
  - IRON_GOLEM
  - PARROT
  - HORSE
  - SLIME